language: node_js
node_js:
- '7'
before_deploy:
- if [ "$TRAVIS_BRANCH" == "master" ]; then gulp makeAppYaml-production; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then gulp makeAppYaml-production; fi
- gulp build;
deploy:
- provider: gae
  project: web-services-staging
  keyfile: client-secret.json
  skip_cleanup: true
  on:
    branch: staging
- provider: gae
  project: web-services-production
  keyfile: client-secret.json
  skip_cleanup: true
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_fd3be96b553d_key -iv $encrypted_fd3be96b553d_iv
  -in client-secret.json.enc -out client-secret.json -d
