FROM node:8.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app/
RUN npm install
RUN npm install -g gulp

EXPOSE 3000

CMD ["gulp", "serve", "--env=staging"]