FROM node:8.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app/
RUN npm install

EXPOSE 3000

CMD ["./node_modules/.bin/gulp", "serve", "--env=staging"]